# Generated by Django 5.0.4 on 2024-04-14 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_company_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='news.company'),
        ),
    ]
