# Generated by Django 5.0.4 on 2024-04-22 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_source_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='users',
        ),
        migrations.AlterUniqueTogether(
            name='story',
            unique_together={('url', 'client')},
        ),
        migrations.AddField(
            model_name='source',
            name='company',
            field=models.ManyToManyField(blank=True, to='news.company'),
        ),
        migrations.AddField(
            model_name='source',
            name='source_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='source',
            name='source_url',
            field=models.URLField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name='story',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='stories', to='news.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_stories', to='news.company'),
        ),
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='published_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='news.source'),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('confirm_password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company', models.ManyToManyField(blank=True, to='news.company')),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='news.users'),
        ),
        migrations.AddField(
            model_name='story',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_stories', to='news.users'),
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('user', 'source_url')},
        ),
        migrations.RemoveField(
            model_name='story',
            name='companies',
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.users')),
            ],
            options={
                'unique_together': {('user', 'company')},
            },
        ),
        migrations.RemoveField(
            model_name='source',
            name='client',
        ),
        migrations.RemoveField(
            model_name='source',
            name='name',
        ),
        migrations.RemoveField(
            model_name='source',
            name='url',
        ),
    ]
