# Generated by Django 5.0.4 on 2024-04-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_company_users_alter_story_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='registeredUsers',
        ),
    ]
