# Generated by Django 5.0.4 on 2024-04-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_story_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_name',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=100000),
        ),
    ]
