# Generated by Django 5.0.4 on 2024-04-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_story_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=2550, unique=True),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='confirm_password',
            field=models.CharField(max_length=1280),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='first_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='last_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='password',
            field=models.CharField(max_length=1280),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_name',
            field=models.CharField(default=None, max_length=1000000),
        ),
    ]
