# Generated by Django 5.0.4 on 2024-04-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='confirm_password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
